(function(a,m,q){function c(a,b){a.super_=b;g.prototype=b.prototype;a.prototype=new g;a.prototype.constructor=a}function g(){}function v(a,b){for(var p in b)b.hasOwnProperty(p)&&(a[p]=b[p]);return a}function n(a,b){return(b=b||q)&&b.getElementById&&b.getElementById(a)}function y(a,b){var p=b?a.substr?n(a):a:q;return p?p.getElementsByTagName(b||a):[]}function B(a,b){return~(" "+a.className+" ").indexOf(" "+b+" ")}function x(a,b){B(a,b)&&(a.className=(" "+a.className+" ").replace(" "+b+" "," ").slice(1,
-1),x(a,b))}function u(a){var p=a.offsetTop,c=a.offsetLeft,d,e=b.curCSS,f="static"!=e(a,"position");p||(p=(parseFloat(e(a,"marginTop"))||0)+(f?parseFloat(e(a,"top"))||0:0));c||(c=(parseFloat(e(a,"marginLeft"))||0)+(f?parseFloat(e(a,"left"))||0:0));f&&a.getBoundingClientRect&&(d=b.offset(a,!0));!p&&d&&(p=d.top);!c&&d&&(c=d.left);return{top:p,left:c}}function H(a){var b={relativeX:a[z[0]],relativeY:a[z[1]]};if(null==a.pageX&&null!=a.clientX){var p=q.documentElement,c=q.body;b.pageX=a.clientX+(p&&p.scrollLeft||
c.scrollLeft||0);b.pageY=a.clientY+(p&&p.scrollTop||c.scrollTop||0)}else b.pageX=a.pageX,b.pageY=a.pageY;return b}function O(a,c){if(!(a=a.parentNode))return!1;var p=a.ownerDocument,d=p.body,e=b.curCSS,U;c&&(c+=1);if(m.$sf)return!0;if(b.isIE&&(8>p.documentMode||"BackCompat"==p.compatMode))return!1;for(;a&&a!=d;){if("hidden"==e(a,"overflow"))return!1;if("fixed"==e(a,"position"))break;else if(c&&(U=parseInt(e(a,"z-index"),10))&&U<c)return!1;a=a.parentNode}return!0}function l(){for(var a=0,b=[];a<X.length;a++)"complete"!=
X[a].document.readyState&&b.push(X[a]);if(!(X=b).length||3E4<(new Date).getTime()-F){E=clearInterval(E);for(a=0;a<M.length;a++)M[a]();M=[];X=[]}}function f(a,b){var p=Math.max(a.x,b.x),c=Math.max(a.y,b.y),d=Math.min(a.x+a.width,b.x+b.width)-p;a=Math.min(a.y+a.height,b.y+b.height)-c;return 0<d&&0<a?{x:p,y:c,width:d,height:a}:{x:0,y:0,width:0,height:0}}function N(a,c,d,e){var p=function(a){e&&e.apply(a,arguments)},f=y(d,"head");f=f&&f[0];if(!f)try{throw Error("Can't find head tag.");}catch(ca){p(ca)}var U=
c.src||c.href,g=U.replace(/[^\da-z_-]/gi,"_"),h=d.adformId||b.gid("doc_"),ba=h+"|"+g,k=Z[ba];g=b.byTag(d,a);var W=0,l=g.length;d.adformId=d.adformId||h;if(k)k.loaded?p():k.callbacks.push(p);else{for(;W<l;++W)if(g[W].src==U||g[W].href==U){p();return}Z[ba]=k={doc:d,src:U,callbacks:[p]};var m=d.createElement(a);v(m,c);if(e){var n=function(a){m.onload=m.onreadystatechange=m.onerror=null;a?Z[ba]=null:k.loaded=1;var b=k.callbacks;W=0;for(l=b.length;W<l;++W)b[W](a)};m.onload=function(){n()};m.onreadystatechange=
function(){"complete"==m.readyState&&n()};m.onerror=function(){try{throw Error("Failed to load script: "+U);}catch(ca){n(ca)}}}setTimeout(function(){f.insertBefore(m,f.firstChild)},400)}}a.Log||(a.Log={});a.Log.pushMessage||(a.Log.pushMessage=function(){});a.Log.sendMessage||(a.Log.sendMessage=function(){});a.RMB=a.RMB||{};var d=a.RMB,b=d.lib||(d.lib={});a.lib||(a.lib=b);b.inherit=c;b.define=function(a,b,d){d&&c(a,b);d(a,a.prototype)};b.gid=function(a){var b=+new Date;return(a||"")+(b+b*~~(1E4*Math.random())).toString(36)};
b.byId=n;b.byTag=y;b.bind=function(a,b){return function(){return b.apply(a,arguments)}};b.extend=v;b.isMouseLeave=function(a,b){if(!a||"mouseout"!=a.type)return!0;a=a.relatedTarget||a.toElement;for(var p,c=b.length;a;){for(p=0;p<c;p++)if(b[p]==a)return!1;a=a.parentNode}return!0};b.singleCall=function(a){function b(){e=!1;var a=c,b=p,f=d;p=c=d=null;a&&a.apply(b,f)}var p,c,d,e;return function(f,g){p=f;c=g;d=w.call(arguments,2);g&&!e?e=setTimeout(b,a):!g&&e&&(clearTimeout(e),e=!1)}};b.onload=function(a,
b){try{do{if(a[Q])break;a[Q]=!0;"complete"!=a.document.readyState&&(X.push(a),E||(F=(new Date).getTime(),E=setInterval(l,200)))}while(a!=a.parent&&(a=a.parent))}catch(ba){}E?M.push(b):setTimeout(b,0)};b.overlap=f;b.overlapElem=function(a,c){var d=b.offset(a),p=b.offset(c);return f({x:d.left,y:d.top,width:a.offsetWidth,height:a.offsetHeight},{x:p.left,y:p.top,width:c.offsetWidth,height:c.offsetHeight})};b.hasClass=B;b.addClass=function(a,b){B(a,b)||(a.className+=" "+b)};b.removeClass=x;b.loadScript=
function(a,b,c){N("script",{src:b,type:"text/javascript"},a,c)};b.loadCSS=function(a,b){N("link",{href:b,type:"text/css",rel:"stylesheet"},a)};b.navigator=m.navigator;b.isTMX=function(a){try{var b=a.document,c=b&&b.body;return c&&B(c,"tmx")}catch(W){}return!1};b.isolate=function(a,b){var c=a.__adform_isolate;if(!c){var d=a.document;c=y(d,"head")[0];d=d.createElement("script");d.type="text/javascript";d.text='function __adform_isolate(f){new Function("window","("+f+")(window)")(window)}';c.insertBefore(d,
c.firstChild);c.removeChild(d);c=a.__adform_isolate}c?c(b):(new Function("window","("+b+")(window)"))(a)};var w=Array.prototype.slice;b.addEvent=function(a,b,c){return a[C]?a[C](b,c,!1):a[h]?a[h]("on"+b,c):!1};b.removeEvent=function(a,b,c){return a[A]?a[A](b,c,!1):a[k]?a[k]("on"+b,c):!1};var C="addEventListener",A="removeEventListener",h="attachEvent",k="detachEvent",t=/([A-Z])/g,r=/^-?\d+(?:px)?$/i,P=/^-?\d/;a=q.defaultView;b.curCSS=a&&a.getComputedStyle?function(a,b){var c=a.ownerDocument.defaultView;
if(c&&(c=c.getComputedStyle(a,null)))return c.getPropertyValue(b.replace(t,"-$1").toLowerCase())||a.style[b]}:q.documentElement.currentStyle&&function(a,b){var c,d,e=a.currentStyle&&a.currentStyle[b];if(!r.test(e)&&P.test(e)){var p=(d=a.style).left;if(c=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;d.left="fontSize"===b?"1em":e||0;e=d.pixelLeft+"px";d.left=p;c&&(a.runtimeStyle.left=c)}return""===e?"auto":e};var Y=function(){function a(){return a}var b=q.body,c=q.createElement("div");
var d=["position:absolute;top:0;left:0;margin:0;padding:0;border:0;width:1px;height:1px;"].pop();c.innerHTML='<div style="'+d+'visibility:hidden"><div style="'+d+'border:5px solid #000"><div style="margin:0"></div></div><div style="'+d+'"><div style="'+d+'position:fixed;top:20px;"></div></div><div style="'+d+'position:relative;border:5px solid #000;overflow:hidden"><div style="margin:0"></div></div><table style="'+d+'border:5px solid #000" cellpadding="0" cellspacing="0"><tr><td></td></tr></table></div>';
b.insertBefore(c=c.firstChild,b.firstChild);d=c.childNodes;a.dnab=5!==d[0].firstChild.offsetTop;a.sfp=20===d[1].firstChild.offsetTop;a.sbfonv=-5===d[2].firstChild.offsetTop;a.dabftac=5===y(c,"td").offsetTop;b.removeChild(c);b=c=d=null;return Y=a},T=/^t(?:able|d|h)$/i;b.offsetFromWindow=function(a){var c=a&&a.ownerDocument;if(!c)return null;var d=c.documentElement;if("getBoundingClientRect"in d){try{var e=a.getBoundingClientRect();var f=d.getBoundingClientRect()}catch(fa){}if(!e)return{top:0,left:0};
if(0<f.left||0<f.top)e.top-=f.top,e.left-=f.left;return{top:e.top,left:e.left}}e=c.defaultView||c.parentWindow;f=c.body;if(a===c.body)return u(a);a=b.offset(a);c=e&&e.pageYOffset||d.scrollTop||f.scrollTop;d=e&&e.pageXOffset||d.scrollLeft||f.scrollLeft;a.top-=c;a.left-=d;return a};b.offset="getBoundingClientRect"in q.documentElement?function(a,b){var c=a&&a.ownerDocument;if(!c)return null;if(!b&&a===c.body)return u(a);try{var d=a.getBoundingClientRect()}catch(ea){}if(!d)return{top:0,left:0};a=c.body;
c=c.documentElement;return{top:d.top+(c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0),left:d.left+(c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0)}}:function(a){var b=a&&a.ownerDocument;if(!b)return null;if(a===b.body)return u(a);var c=a.offsetParent,d=b.documentElement,e=b.body;var f=(b=b.defaultView)?b.getComputedStyle(a,null):a.currentStyle;for(var g=a.offsetTop,h=a.offsetLeft,k=Y();(a=a.parentNode)&&a!==e&&a!==d&&(!k.sfp||"fixed"!==f.position);)f=b?b.getComputedStyle(a,null):
a.currentStyle,g-=a.scrollTop,h-=a.scrollLeft,a===c&&(g+=a.offsetTop,h+=a.offsetLeft,!k.dnab||k.dabftac&&T.test(a.nodeName)||(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0),c=a.offsetParent),k.sbfonv&&"visible"!==f.overflow&&(g+=parseFloat(f.borderTopWidth)||0,h+=parseFloat(f.borderLeftWidth)||0);if("relative"===f.position||"static"===f.position)g+=e.offsetTop,h+=e.offsetLeft;k.sfp&&"fixed"===f.position&&(g+=Math.max(d.scrollTop,e.scrollTop),h+=Math.max(d.scrollLeft,e.scrollLeft));
return{top:g,left:h}};b.client=function(a){a=a.ownerDocument||a;var b=a.defaultView||a.parentWindow;var c=a.documentElement;var d=a.body;if(b.innerWidth){a=b.innerWidth;var e=b.innerHeight}else c?(a=c.clientWidth,e=c.clientHeight,a&&d.clientHeight==d.offsetHeight||(a=Math.min(a||123456789,d.clientWidth||123456789),e=Math.min(e||123456789,d.clientHeight||123456789))):(a=d.clientWidth,e=d.clientHeight);return{left:b&&b.pageXOffset||c&&c.scrollLeft||d&&d.scrollLeft||0,top:b&&b.pageYOffset||c&&c.scrollTop||
d&&d.scrollTop||0,width:a,height:e}};b.isArray=Array.isArray||function(a){return"[object Array]"==Object.prototype.toString.call(a)};var z=[["offsetX","offsetY"],["layerX","layerY"]];b.getMousePos=function(a){for(var c;c=z.shift();)if("undefined"!=typeof a[c[0]]){z=c;break}c||(z=["x","y"]);b.getMousePos=H;return H(a)};var I=q.createElement("div");b.html=function(a,b){b=!b&&I||b.createElement("div");b.innerHTML=a;return b.firstChild&&b.removeChild(b.firstChild)};a=b.navigator;var D=a.vendor;a=a.userAgent;
var V=/Apple Computer/i.test(D);d=/Google/i.test(D);var R=b.isIPad=/iPad/i.test(a),L=b.isIPhone=/iPhone/i.test(a),G=b.isIOS=R||L,J=b.isTouch="ontouchstart"in q.documentElement||"ontouchstart"in m;R=b.isOrientation="orientation"in m;L=b.isAndroid=!G&&/Android/i.test(a);b.isAndroidApp=L&&!/^(?:Opera|Mozilla)/i.test(a);var K;b.isIOSF=G&&(K=/\sos\s(\d+)_\d+/i.exec(a))&&(K=4<K[1]>>0);var e=b.isMobile=/Mobile|Mobi|Tablet|Nokia/i.test(a)||J;K=b.isIE=/msie|Trident/i.test(a);J=b.isFF=/Firefox[\/.]+[^\s]/i.test(a);
b.isMACOS=/Mac OS X/i.test(a);(b.isWinPhone=K&&e&&/Phone/gi.test(a))&&(e=/Windows Phone (OS )?(\d+[\.\d]*)/i.exec(a))&&e[2]&&(b.winPhoneVer=parseFloat(e[2]));e=b.isOpera=/Opera/i.test(a);var S=b.isOperaMobile=/Opera\s(?!Mini)/i.test(a),aa=b.isOperaMini=/Opera\sMini/i.test(a);D=b.isOperaWebKit=/OPR/i.test(a)&&/Opera Software/i.test(D);G=b.isChrome=/(Chrome|CriOS)+\/[\d\.]+\s/i.test(a)&&(G?V:d);V=b.isSafari=!/Chrome|CriOS|Skyfire/i.test(a)&&/Safari+\/[\.\d]+$/i.test(a)&&V;d=b.isInternet=L&&!G&&R&&/Safari\/[\.\d]+$/i.test(a)&&
d;b.isEdge=/Edge\/[\.\d]+$/i.test(a);b.isAfmaSDK=/afma-sdk/i.test(a);var da=K?"msie":J?"firefox":S?"operaMobile":aa?"operaMini":e?"opera":D?"operaWebKit":G?"chrome":V?"safari":d?"internet":!1;b.browser=function(){return da};b.isIE&&("Microsoft Internet Explorer"==b.navigator.appName&&/MSIE (\d+[\.\d]*)/i.exec(a)||/rv:(\d+[\.\d]*)/i.exec(a))&&(b.ieVersion=parseFloat(RegExp.$1));b.testPlace=b.isIE&&8>b.ieVersion?function(){return!1}:O;b.isSafari&&(a=/Version.([\d.]+)/.exec(a),b.safariVersion=parseFloat(a&&
a[1]));var X=[],M=[],Q="__adform_onload",E,F,Z={}})(Adform=window.Adform||{},window,document);
(function(a){function m(){}a.RMB=a.RMB||{};a.RMB.EventEmitter=m;var q=Array.prototype.slice;a=m.prototype;a.emit=function(a){var c=this._events,v=!1,n=arguments;if(c&&(c=c[a]))if("function"==typeof c){switch(n.length){case 1:c.call(this);break;case 2:c.call(this,n[1]);break;case 3:c.call(this,n[1],n[2]);break;case 4:c.call(this,n[1],n[2],n[3]);break;default:c.apply(this,q.call(n,1))}v=!0}else if(c.length){n=q.call(n,1);c=c.slice();v=0;for(var m=c.length;v<m;v++)c[v].apply(this,n);v=!0}else delete this._events[a];
return v};a.on=function(a,g){this._events||(this._events={});this.emit("newListener",a,g);var c=this._events;c[a]?"function"==typeof c[a]?c[a]=[c[a],g]:c[a].push(g):c[a]=g;return this};a.once=function(a,g){var c=g._once;c?c._times++:(c=g._once=function(){this.off(a,c);1>--c._times&&delete g._once;return g.apply(this,arguments)},c._times=1);return this.on(a,c)};a.off=function(a,g){if(!this._events||!this._events[a])return this;var c=this._events,n=c[a];if(n==g)return delete c[a],this;g&&g._once&&this.off(g._once);
if("function"==typeof n)return this;if(2>n.length&&n[0]==g)return delete c[a],this;for(var m=0,q=n.length,x=[];m<q;m++)n[m]!=g&&x.push(n[m]);x.length!=q&&(x.length?c[a]=x:delete c[a]);return this};a.clear=function(a){a?this._events&&this._events[a]&&delete this._events[a]:delete this._events;return this};a.list=function(a){this._events||(this._events={});var c=this._events;c[a]?"function"==typeof c[a]&&(c[a]=[c[a]]):c[a]=[];return c[a]}})(Adform=window.Adform||{});
/*
 mustache.js - Logic-less {{mustache}} templates with JavaScript
 http://github.com/janl/mustache.js
*/
(function(a,m,q){function c(a){return parseInt(a,10)?a:0}function g(){}function v(a,g,c){function l(){d=!1;var b=u;u=[];c(function(a){for(var d=0;d<b.length;d++)if(a)b[d][1](a);else f(b[d][0],b[d][1])})}function f(b,w){var f=!1;g(b,function(){f=!0;w.apply(this,arguments)});f||(u.push([b,w]),d||(d=setTimeout(l,a)))}var u=[],d=!1;return f}function n(a,g,c){var l=a["@id"]||0;var f=a["@pdata"]||"";var u={$id:l,$name:a["@name"]||"default",$link:c.replace(/adfibeg=\d+/,f?"pdata="+f:"adfibeg="+l),$pdata:f};
if(a.TextVars)for(c=0,l=a.TextVars.TextVar,f=l.length,x.isArray(l)||(l=[l],f=1);c<f;c++){var d=l[c];var b=d["@name"];d=d["@value"];u[b]=d;"product_deeplink"==b&&(u.$link+=";cpdir="+encodeURIComponent(d))}if(a.Graphics)for(c=0,l=a.Graphics.Graphic,f=l.length,x.isArray(l)||(l=[l],f=1);c<f;c++)d=l[c],u[d["@name"]]=g+d["@value"]+"?assetID="+d["@assetID"]+"&av="+d["@av"];return u}function y(a,c,g){var l=a.root;a={};if(l.TextVars||l.Graphics)a[0]=a[""]=n(l,c,g);if(l.Groups){var f=0,u=l.Groups.Group,d;x.isArray(u)||
(u=[u]);for(d=u.length;f<d;f++){var b=n(u[f],c,g);a[b.$id]=b}}c=l.GroupIds?l.GroupIds.split(","):[];return{ids:c,items:a,total:c.length}}var B=a.AdMessage||(a.AdMessage={}),x=a.lib;B.build=function(a){function u(){var e=L?L.length:0;return{total:e,totalPages:Math.ceil(e/d),pageSize:d,ids:L||[],limit:q}}function n(e,a,b){B.load(P[e]+"&"+a,function(e,a){e?b(e):b(null,y(a,t,k))})}function l(e){if(e)for(var a in e)e.hasOwnProperty(a)&&(R[a]=e[a])}var f=m.dhtml&&dhtml.getVar()||{},q=c(a.limit)||100,d=
c(a.pageSize)||1,b=c(a.cid||f.cid),w=c(a.tid||f.tid),C=c(a.tv||f.tv)||+new Date,A=c(a.bn||f.bn),h=a.gid||f.gid||0,k=a.clickTAG||"",t=(a.statics||a.domain||f.staticDomain||f.domain).replace(/\/+$/,""),r=(a.domain||f.domain).replace(/(\w+:\/\/[^\/]+\/).*/,"$1"),P={adMessage:r+"Serving/AdMessage/?",recommendations:r+"dco/recommendations/?",products:r+"dco/products/?"};b="aid="+b+"&tid="+w+"&tv="+C;w=c(a.icid||f.icid)||"0";C=f.unloadID||"0";r=f.geo||"0;0;0";var Y=a.eshopId||f.trackingSetupId||"0",T=f.ADFbanID||
"0",z=c(a.rotseqno||f.rotseqno),I=a.smid||f.smid,D=a.dcoEngineId||f.dcoEngineId;f.versionListId&&(b+="&versionListId="+f.versionListId);f.versionId&&(b+="&versionId="+f.versionId);w&&(b+="&icid="+w);Y&&(b+="&eid="+Y);z&&(b+="&rotseqno="+z);I&&(b+="&smid="+I);D&&(b+="&dco="+D);T&&(b+="&bnrid="+T);C&&(b+="&intid="+C);r&&(b+="&geo="+r.split(";").join(","));for(var V in P)P[V]+=b;var R={},L,G=0,J=v(100,function(e,a){e*=d;var b=e+2*d;G=Math.max(G,b);if(L)if(e=L.slice(e,b),e.length)a(null,e,u());else try{throw Error("AdMessage page not found.");
}catch(M){a(M)}},function(e){n(D?"recommendations":"adMessage","bn="+A+"&gcnt="+q+"&pgsz="+Math.min(G,q),function(a,b){if(a)e(a);else if(l(b.items),(L=b.ids)&&L.length)e();else try{throw Error("AdMessage template doesn't contain groups.");}catch(M){e(M)}});G=0}),K={},e=[],S=v(100,function(a,b){for(var h=a._test||0,k=[],d=0,w=a.length,S,t;d<w;d++)(t=R[S=a[d]])?k.push(t):K[S]||(K[S]=!0,e.push(S));a._test=++h;if(k.length==a.length)b(null,k,u());else if(4<h)try{throw Error("AdMessage group"+((1<a.length?
's "':' "')+a.join(", "))+'" not found.');}catch(p){b(p)}},function(a){e.length?n(D?"products":"adMessage","bn="+A+"&gid="+e.join(","),function(e,b){K={};e?a(e):(l(b.items),a())}):setTimeout(function(){a()},100);e=[]});f.dynamicAdContent&&l(y(f.dynamicAdContent,t,k).items);return{setProperties:function(e){var a=e.pageSize>>0||d;e=e.limit>>0||q;0<e&&(q=e);0<a&&(d=Math.min(a,q))},getProperties:u,getPage:function(e,a){J((e>>0)-1,function(e,b){e?a(e):(S(b.slice(0,d),a),S(b.slice(d),g))})},getItems:function(e,
a){S(x.isArray(e)?e:[e],a)},getDefault:function(e){S([h],function(a,b,h){e(a,b&&b[0],h)})}}};B.load=function(a,c){var g=x.gid("adform_com_"),l=q.createElement("script"),f=function(){d();try{throw Error("AdMessage load error.");}catch(b){c(b)}},v=function(a){d();c(null,a)},d=function(){l.parentNode.removeChild(l);m[g]=l.onerror=l.onload=f=v=d=l=null};l.type="text/javascript";l.src=a+"&format=json&callback="+encodeURIComponent(g);l.onload=l.onerror=function(){setTimeout(f,1E3)};m[g]=v;a=x.byTag(q,"script")[0];
a.parentNode.insertBefore(l,a)}})(Adform=window.Adform||{},window,document);
(function(a,m,q,c){function g(){}function v(a){for(var b=f.length;0<b--;)if(f[b][0]==a)return f[b][1]}function n(a,c,g){function h(e){if(e&&w)b(w,"touchstart",H);else if(!w)try{(w=a.defaultView.frameElement)&&d(w,"touchstart",H)}catch(S){}}var k=v(a),t,r;k?t=k._:f.push([a,k={_:t=new l,_destroy:function(){t.clear();delete this._;delete this._destroy;for(var b in this)if("function"==typeof this[b])this[b]();for(b=f.length;0<b--;)if(f[b][0]==a){f.splice(b,1);break}}}]);var P,w,C,z,q,n,A,u;O.isIOS&&a.defaultView.frameElement&&
{click:1,mousedown:1,mouseup:1}[c]&&d(g,c,H);if(!k[c])switch(c){case "swipe":var m=function(a){if(P=x(t,a.target,"swipe")[0])a.preventDefault(),(a=a&&a.targetTouches)&&(a=a[0])&&(C=a.pageX,q=a.pageY,A=(new Date).getTime())};var G=function(a){var b=a&&a.targetTouches;P&&(a.preventDefault(),b&&(b=b[0])&&A&&(z=b.pageX,n=b.pageY,u=(new Date).getTime(),.2<Math.sqrt(Math.pow(z-C,2)+Math.pow(n-q,2))/(u-A)&&(a=q-n,b={type:"swipe"},b.directionX=0<C-z?"left":"right",b.directionY=0<a?"up":"down",b.target=P[1],
A=0,B(t,P[1],b))))};d(a,"touchstart",m);d(a,"touchend",G);d(a,"touchmove",G);h();k[c]=function(){b(a,"touchstart",m);b(a,"touchend",G);b(a,"touchmove",G);h(!0)};break;case "hover":if(a.addEventListener){var J=function(a){a=a.target;r!=a&&y(t,r,r=a)};var K=function(a){a=a.relatedTarget;r!=a&&y(t,r,r=a)}}else J=function(b){b=(a.defaultView||a.parentWindow).event.srcElement;r!=b&&y(t,r,r=b)},K=function(b){b=(a.defaultView||a.parentWindow).event.toElement;r!=b&&y(t,r,r=b)};d(a,"mouseover",J);d(a,"mouseout",
K);d(a,"mousemove",J);k[c]=function(){b(a,"mouseover",J);b(a,"mouseout",K);b(a,"mousemove",J);r=null};break;case "click":case "mousedown":case "mouseup":case "touchstart":case "touchmove":case "touchend":J=a.addEventListener?function(a){B(t,a.target,a)}:function(b){b=(a.defaultView||a.parentWindow).event;B(t,b.srcElement,b)},d(a,c,J),k[c]=function(){b(a,c,J)}}return!!k[c]}function y(a,b,d){d=x(a,d,"hover");b=x(a,b,"hover");for(var h=d.length,k=h,c=b.length,r=c-h;0<k--&&d[k][1]==(b[r+k]&&b[r+k][1]););
d.length=h=k+1;b.length=c=r+k+1;var g,f=a._events;if(f){for(r=k=-1;++r<c;)f[g=b[r][0]]&&a.emit(g,b[r][1],"hoverout");for(;++k<h;)f[g=d[k][0]]&&a.emit(g,d[k][1],"hoverin")}}function B(a,b,d,h){h=h||d;b=x(a,b,d.type);d=b.length;for(var k=0,c;c=b[k],k++<d;)a.emit(c[0],c[1],h)}function x(a,b,d){a=a._events;var h,k,c,g=[];if(a)for(;b&&"undefined"!=(c=typeof(k=b.className));)"string"==c&&~k.indexOf("adform-dom-")&&a[h=u(b)+":"+d]&&(g[g.length]=[h,b]),b=b.parentNode;return g}function u(a){a=a.className;
return~a.indexOf("adform-dom-")?a.match(N)[1]:O.gid()}function H(){}a.RMB=a.RMB||{};a=a.RMB;a.DOMEvents=g;var O=a.lib,l=a.EventEmitter,f=[],N=/adform-dom-(\S+)/,d=O.addEvent,b=O.removeEvent;g.has=function(a){return!!{hover:1,mousedown:1,mouseup:1,click:1,swipe:1,touchstart:1,touchmove:1,touchend:1}[a]};g.on=function(a,b,d){var h=a.ownerDocument;if(n(h,b,a)){var c=u(a);O.addClass(a,"adform-dom-"+c);v(h)._.on(c+":"+b,d);return!0}return!1};g.off=function(a,b,d){v(a.ownerDocument)._.off(u(a)+":"+b,d)};
g.destroy=function(a){v(a)._destroy()}})(Adform=window.Adform||{},window,document);
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(a){function m(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return C[a]||a})}function q(a,b,d,c){c=c||"<template>";var h=b.split("\n"),k=Math.max(d-3,0);h=h.slice(k,Math.min(h.length,d+3));for(var g,f=0,r=h.length;f<r;++f)g=f+k+1,h[f]=(g===d?" >> ":"    ")+h[f];a.template=b;a.line=d;a.file=c;a.message=[c+":"+d,h.join("\n"),"",a.message].join("\n");return a}function c(a,b,d){if("."===a)return b[b.length-1];a=a.split(".");for(var h=a.length-1,c=a[h],k,g,f=b.length,t,l;f;){l=
b.slice(0);g=b[--f];for(t=0;t<h;){g=g[a[t++]];if(null==g)break;l.push(g)}if(g&&"object"===typeof g&&c in g){k=g[c];break}}"function"===typeof k&&(k=k.call(l[l.length-1]));return null==k?d:k}function g(a,b,d,g){var h="";a=c(a,b);if(g){if(null==a||!1===a||l(a)&&0===a.length)h+=d()}else if(l(a))f(a,function(a){b.push(a);h+=d();b.pop()});else if("object"===typeof a)b.push(a),h+=d(),b.pop();else if("function"===typeof a){var k=b[b.length-1];h+=a.call(k,d(),function(a){return B(a,k)})||""}else a&&(h+=d());
return h}function v(b,c){c=c||{};for(var h=c.tags||a.tags,g=h[0],k=h[h.length-1],f=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],l=[],v=!1,n=!1,u=function(){if(!v||n||c.space)l=[];else for(;l.length;)f.splice(l.pop(),1);n=v=!1},m=[],y,w,x,B=function(a){h=d(a).split(/\s+/);w=h[0];x=h[h.length-1]},A=function(a){f.push('";',y,'\nvar partial = partials["'+d(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},e=function(a,
U){a=d(a);if(""===a)throw q(Error("Section name may not be empty"),b,M,c.file);m.push({name:a,inverted:U});f.push('";',y,'\nvar name = "'+a+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},C=function(a){e(a,!0)},H=function(a){a=d(a);var p=0!=m.length&&m[m.length-1].name;if(!p||a!=p)throw q(Error('Section named "'+a+'" was never opened'),b,M,c.file);a=m.pop();f.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?f.push("\nbuffer += renderSection(name,stack,callback,true);"):
f.push("\nbuffer += renderSection(name,stack,callback);");f.push('\nbuffer += "')},O=function(a){f.push('";',y,'\nbuffer += lookup("'+d(a)+'",stack,"");','\nbuffer += "')},X=function(a){f.push('";',y,'\nbuffer += escapeHTML(lookup("'+d(a)+'",stack,""));','\nbuffer += "')},M=1,Q,E,F=0,Z=b.length;F<Z;++F)if(b.slice(F,F+g.length)===g){F+=g.length;Q=b.substr(F,1);y="\nline = "+M+";";w=g;x=k;v=!0;switch(Q){case "!":F++;E=null;break;case "=":F++;k="="+k;E=B;break;case ">":F++;E=A;break;case "#":F++;E=e;
break;case "^":F++;E=C;break;case "/":F++;E=H;break;case "{":k="}"+k;case "&":F++;n=!0;E=O;break;default:n=!0,E=X}Q=b.indexOf(k,F);if(-1===Q)throw q(Error('Tag "'+g+'" was not closed properly'),b,M,c.file);g=b.substring(F,Q);E&&E(g);for(E=0;~(E=g.indexOf("\n",E));)M++,E++;F=Q+k.length-1;g=w;k=x}else switch(Q=b.substr(F,1),Q){case '"':case "\\":n=!0;f.push("\\"+Q);break;case "\r":break;case "\n":l.push(f.length);f.push("\\n");u();M++;break;default:N.test(Q)?l.push(f.length):n=!0,f.push(Q)}if(0!=m.length)throw q(Error('Section "'+
m[m.length-1].name+'" was not closed properly'),b,M,c.file);u();f.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");k=f.join("").replace(/buffer \+= "";\n/g,"");c.debug&&("undefined"!=typeof console&&console.log?console.log(k):"function"===typeof print&&print(k));return k}function n(a,b){var d=v(a,b),h=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",d);return function(d,f){f=f||{};var k=[d];try{return h(d,f,k,c,m,g,B)}catch(z){throw q(z.error,
a,z.line,b.file);}}}function y(a,b){b=b||{};return!1!==b.cache?(A[a]||(A[a]=n(a,b)),A[a]):n(a,b)}function B(a,b,d){return y(a)(b,d)}a.name="mustache.js";a.version="0.5.0-dev";a.tags=["{{","}}"];a.parse=v;a.compile=y;a.render=B;a.clearCache=function(){A={}};a.to_html=function(a,b,d,c){a=B(a,b,d);if("function"===typeof c)c(a);else return a};var x=Object.prototype.toString,u=Array.isArray,H=Array.prototype.forEach,O=String.prototype.trim;var l=u?u:function(a){return"[object Array]"===x.call(a)};var f=
H?function(a,b,d){return H.call(a,b,d)}:function(a,b,d){for(var c=0,g=a.length;c<g;++c)b.call(d,a[c],c,a)};var N=/^\s*$/;if(O)var d=function(a){return null==a?"":O.call(a)};else{if(N.test("\u00a0")){var b=/^\s+/;var w=/\s+$/}else b=/^[\s\xA0]+/,w=/[\s\xA0]+$/;d=function(a){return null==a?"":String(a).replace(b,"").replace(w,"")}}var C={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"},A={}})(Mustache);
(function(a,m,q){function c(){if(m.Ready)for(var e=0;e<Ready.length;e++)n(Ready[e]);m.Ready={push:n}}function g(e,a){var b=t,h="undefined"==typeof t[e],d="undefined"==typeof k[e];e&&(b=h&&d?a:h?k[e]:t[e]);return b}function v(e){e=parseInt(e,10);var a=g("videoSources");if(a)for(var b=a.length,h,k=0;k<b;k++)if(h=a[k],h.id==e)return h.file}function n(e){e.call(m);K||(clearTimeout(J),J=setTimeout(function(){K=!0;q.close()},1E3))}function y(e,a){"function"==typeof a&&(e=a);try{throw Error("AdMessage template id is missing");
}catch(aa){if("function"==typeof e)e(aa);else throw aa;}}function B(e,a,b,d){var w=m._Adform&&_Adform.Events;if(w&&w.sendEvent){if(e in z)a=z[e];else if(isNaN(e=parseInt(e,10))||1>e||20<e&&200>e||250<e)throw Error("Custom event id="+e+" must be between 1-20 for engaging and 200-250 for non-engaging events");if(!a)throw Error("Event name is missing");var t=[""];if(b)for(var c in b){var r=c.slice(0,2),g=parseInt(c.slice(2),10);"bv"==r&&0<g&&256>g&&t.push(c+"="+encodeURIComponent(b[c]))}d&&t.push(d);
w.sendEvent(k.xId,e,h.assetId,a,t.join("&"),"Standard HTML");return!0}return!1}function x(a,b){l[a]||(l[a]=Mustache.compile(u(a).text));if(b){if(N.length!=w){for(var e=0;e<N.length;e++)"text/mustache"==N[e].type&&x(N[e].id);w=N.length}return l[a](b,l)}return l[a]}function u(a){return q.getElementById(a)}(function(){var a=m.open;"attributionSrc"in new m.Image&&(m.open=function(e,b,h){return a.call(m,e,b,h?h+",attributionsrc":"attributionsrc")})})();for(var H=a.RMB.lib,O=H.isArray,l={},f,N=q.getElementsByTagName("script"),
d=0,b;d<N.length;d++)if(b=(N[d].src||"").match(/(^.*)rmb\/Adform\.DHTML\.js/)){f=b[1]+"components/";break}var w=0,C=a.RMB.EventEmitter;b=a.RMB.DOMEvents;var A=m._AdformContent||{},h=A.data||{},k=A.options||{},t=h.flashvars,r=a.tagData;if(!t&&(t={},r)){d=r.customVariables;r=r.clickUrls;if(d)for(var P in d)t[P]=d[P];for(var Y in r)t[Y]=r[Y]}var T=new C;a.on=function(){T.on.apply(T,arguments)};a.off=function(){T.off.apply(T,arguments)};a.emit=function(){T.emit.apply(T,arguments)};var z={151:"Previous Product Button Press",
150:"Next Product Button Press",143:"Banner Collapse",22:"Other Expands",21:"First Expand",168:"Auto Expands",161:"Hide Expanding Banner Button Press",23:"Close Button Press",25:"Video Play Start",26:"Played 25% Of Video",27:"Played 50% Of Video",28:"Played 75% Of Video",29:"Video Playback Complete",30:"Play Button Press",31:"Pause Button Press",32:"Stop Button Press",33:"Sound On Button Press",34:"Sound Off Button Press",35:"Full Screen On Button Press",36:"Full Screen Off Button Press",38:"Rewind Button Press",
"":""};a.EVENT_FIRST_EXPAND=[21,z[21]];a.EVENT_OTHER_EXPAND=[22,z[22]];a.EVENT_CLOSE=[23,z[23]];a.EVENT_COLLAPSE=[143,z[143]];for(d=1;251>d;d++)if(21>d||199<d)a["EVENT_CUSTOM_"+d]=[d,"Custom Event "+d];a.sendRequest=function(a){(new Image).src=a};a.sendEvent=function(a){var e,b,h=arguments;if(e=O(a)&&1<a.length){for(e=1;e<h.length&&256>e;e++)(b=b||{})["bv"+e]=h[e];e=B(a[0],a[1],b)}return e};a.getClickURL=function(a,b){return g(a||h.defaultClickTAG||"clickTAG",b)||null};a.getLocation=function(){var a=
m._Adform&&_Adform.locationInfo||null;a&&(a.lng=a.Longitude,a.lat=a.Latitude);return a};a.getAsset=function(a){return v(a)||null};a.getVar=function(a){return a&&void 0!==t[a]?t[a]:null};var I=m.dhtml={PREVIOUS_BUTTON_PRESS:151,NEXT_BUTTON_PRESS:150,CLOSE_BUTTON_PRESS:23,COLLAPSE_EVENT:143,EXPAND_EVENT:22,FIRST_EXPAND_EVENT:21,AUTO_EXPAND_EVENT:168,SUPER_CLOSE_EVENT:161,VIDEO_PROG_0:25,VIDEO_PROG_25:26,VIDEO_PROG_50:27,VIDEO_PROG_75:28,VIDEO_PROG_100:29,PLAY_BUTTON_PRESS:30,PAUSE_BUTTON_PRESS:31,STOP_BUTTON_PRESS:32,
SOUND_ON_BUTTON_PRESS:33,SOUND_OFF_BUTTON_PRESS:34,FULL_SCREEN_ON_BUTTON_PRESS:35,FULL_SCREEN_OFF_BUTTON_PRESS:36,REWIND_BUTTON_PRESS:38,byId:u,hasClass:H.hasClass,addClass:H.addClass,removeClass:H.removeClass,mustache:x,sendEvent:function(a,b,h){I.sharedEvents.emit(a+"",{id:a,name:b||z[a],vars:h});if(!(D&&D.callDHTMLEvent&&D.callDHTMLEvent.call(D,a)))return a in z&&(h=null),B(a,b,h)},$sendEvent:B,appendEvents:function(a){for(var e in a)z.hasOwnProperty(e)||(z[e]=a[e]);return z},getVar:g,getAsset:v,
width:h.width,height:h.height,collapsedWidth:k.colWidth,collapsedHeight:k.colHeight,external:A.external||{},inscreen:new C,sharedEvents:A.sharedEvents||new C,scriptsBase:k.scriptsBase||f+"../",getState:function(){return A.state?A.state():"visible"},on:b.on,off:b.off,connect:function(a){var e=m._Adform&&_Adform.ADFUtilInstance;a=a||t.bn||"x";e=e?e.getRotSeed():{};e.localConnections||(e.localConnections={});var b=e.localConnections[a];if(!b){b=new C;var h=[];b.expect=function(a,e){if(h.length>=a)e();
else b.once("expect:"+a,e);return b};b.join=function(a){h.push(a);b.emit("member",a);b.emit("expect:"+h.length);return b};b.members=h;e.localConnections[a]=b}return b}};try{var D=parent.parent.getVPAIDAd&&parent.parent.getVPAIDAd()}catch(e){}if(D&&D.callDHTMLEvent){I.vpaid=D;var V=I.external.close;I.external.close=function(){D.callDHTMLEvent.call(D,23);return V.apply(this,arguments)}}I.sharedEvents.on("newListener",function(a){"pageLoadComplete"==a&&setTimeout(function(){I.external.initPoliteMode()},
0)});I.adMessage=t.tid?a.AdMessage.build({limit:100,pageSize:5}):{setProperties:y,getProperties:y,getPage:y,getItems:y,getDefault:y};var R=I.inscreen;I.external.initInScreen&&(I.sharedEvents.on("updateInScreen",function(a){for(var b in a)R.emit(b,R[b]=a[b]);R.emit("change")}),a.on("newListener",function(b){"visibilityData"===b&&(a.off("newListener",arguments.callee),R.on("change",function(){a.emit("visibilityData",{isVisible:R.visible,visibleArea:R.percent})}))}),R.once("newListener",function(){setTimeout(function(){I.external.initInScreen()},
0)}));components=m.preloadQueue||m.components||[];var L=components.length;for(d=0;d<components.length;d++)q.write('<script src="'+(f+"Adform."+components[d]+".js?bv="+(t.bv||Math.random()))+'">\x3c/script>');try{var G=q.defaultView.frameElement;G&&H.addEvent(G,"touchstart",function(){})}catch(e){}I.registerComponent=function(a){for(var b=0;b<components.length;b++)components[b]==a&&L--;L||c()};L||c();var J,K})(Adform=window.Adform,window,document);
